# SPDX-FileCopyrightText: 2017-2026 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

[tools]
devcontainer-cli = "0.83.2"
java = "zulu-25"
lefthook = "2.1.6"
node = "24.15.0"
"npm:pm2" = "6.0.14"
uv = "0.11.7"
"pipx:reuse" = "6.2.0"
yarn = "4.12.0"

[tasks.sandbox]
description = "Manage the Colima VM sandbox"
dir = ".sandbox"
usage = 'arg "[args]" var=#true'
run = "node sandbox.mjs {{arg(name='args')}}"
