# SPDX-FileCopyrightText: 2023-2025 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

app:
  jwt:
    public_keys_url: classpath:local-development/jwks.json

luontotieto:
  aws:
    region: "eu-north-1"
  s3mock:
    url: "https://${S3_HOST:localhost}:${S3_PORT:9876}"
  bucket:
    data: "data"
    proxy_through_nginx: false
    verify_file_av_tagged: false
  email:
    enabled: "false"
    region: "fake"
    sender_address: "fake"
    sender_arn: "fake"
  host: "http://localhost:9000"
  geoserver:
    base_url: "http://localhost:8000/"
    username: "admin"
    password: "password"

spring:
  datasource:
    luontotieto:
      jdbcUrl: "jdbc:postgresql://${LUONTOTIETO_DB_HOST:localhost}:${LUONTOTIETO_DB_PORT:5432}/luontotieto_it"
      username: "luontotieto"
      password: "postgres"
    paikkatieto:
      jdbcUrl: "jdbc:postgresql://${PAIKKATIETO_DB_HOST:localhost}:${PAIKKATIETO_DB_PORT:5433}/paikkatietodb_it"
      username: "paikkatietodb"
      password: "postgres"
