# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

luontotieto:
  aws:
    region: ${AWS_REGION}
  bucket:
    data: ${DATA_BUCKET}
    proxy_through_nginx: true
  email:
    enabled: ${EMAIL_ENABLED}
    region: ${EMAIL_AWS_REGION}
    sender_address: ${EMAIL_SENDER_ADDRESS}
    sender_arn: ${EMAIL_SENDER_ARN}
  host: ${BASE_URL}

spring:
  main:
    banner-mode: "off"
  application:
    name: "luontotieto-service"
  datasource:
    luontotieto:
      driver-class-name: "org.postgresql.Driver"
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: ${LUONTOTIETO_URL}
      username: ${LUONTOTIETO_USERNAME}
      password: ${LUONTOTIETO_PASSWORD}
      hikari:
        data-source-properties:
          socketTimeout: 30000
    paikkatieto:
      driver-class-name: "org.postgresql.Driver"
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: ${PAIKKATIETO_URL}
      username: ${PAIKKATIETO_USERNAME}
      password: ${PAIKKATIETO_PASSWORD}
      hikari:
        data-source-properties:
          socketTimeout: 30000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      continue-on-error: false
      encoding: "UTF-8"
