# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

app:
  jwt:
    public_keys_url: classpath:local-development/jwks.json

luontotieto:
  aws:
    region: "eu-north-1"
  s3mock:
    url: "https://localhost:9876"
  bucket:
    data: "data"
    proxy_through_nginx: false
    verify_file_av_tagged: false
  email:
    enabled: "true"
    region: "eu-west-1"
    sender_address: "luontotieto@espoo.fi"
    sender_arn: "arn:aws:ses:eu-west-1:758397969161:identity/luontotieto@espoo.fi"
  host: "http://localhost:9000"

spring:
  datasource:
    luontotieto:
      jdbcUrl: "jdbc:postgresql://localhost:5432/luontotieto"
      username: "luontotieto"
      password: "postgres"
    paikkatieto:
      jdbcUrl: "jdbc:postgresql://localhost:5433/paikkatietodb"
      username: "paikkatietodb"
      password: "postgres"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB