# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: '3.5'

services:
  luontotieto-db:
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - luontotieto-db-data:/var/lib/postgresql/data
      - ./db/test-db.sh:/docker-entrypoint-initdb.d/test-db.sh
    environment:
      POSTGRES_DB: luontotieto
      POSTGRES_USER: luontotieto
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(redis-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5
  
  paikkatieto-db:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./db/test-paikkatieto-db.sh:/docker-entrypoint-initdb.d/test-paikkatieto-db.sh
    environment:
      POSTGRES_DB: paikkatietodb
      POSTGRES_USER: paikkatietodb
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "exit 0"

  s3-mock:
    image: adobe/s3mock
    ports:
    - "9876:9191"
    volumes:
    - s3-data:/data
    environment:
      ROOT: /data
      initialBuckets: "static"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  luontotieto-db-data:
    driver: local
  s3-data:
    driver: local
